In [1]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("../data/cleaned_data.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
print(df.shape)
print(df.columns.tolist())

(9994, 21)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [3]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///superstore.db")

df.to_sql("sales", engine, if_exists="replace", index=False)

print("Database created successfully!")

Database created successfully!

In [2]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///superstore.db")

In [4]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("../data/cleaned_data.csv")

print(df.shape)

(9994, 21)

In [5]:
engine = create_engine("sqlite:///superstore.db")

df.to_sql("sales", engine, if_exists="replace", index=False)

print("Database created successfully!")

Database created successfully!

In [6]:
query = """
SELECT *
FROM sales
LIMIT 5;
"""

result = pd.read_sql(query, engine)

result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
query = """
SELECT 
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)

result

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [12]:
query = """
SELECT 
    strftime('%Y-%m', "Order Date") AS Month,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Month
ORDER BY Month;
"""

monthly_sales = pd.read_sql(query, engine)

monthly_sales

      Month  Total_Sales
0   2014-01     14236.90
1   2014-02      4519.89
2   2014-03     55691.01
3   2014-04     28295.35
4   2014-05     23648.29
5   2014-06     34595.13
6   2014-07     33946.39
7   2014-08     27909.47
8   2014-09     81777.35
9   2014-10     31453.39
10  2014-11     78628.72
11  2014-12     69545.62
12  2015-01     18174.08
13  2015-02     11951.41
14  2015-03     38726.25
15  2015-04     34195.21
16  2015-05     30131.69
17  2015-06     24797.29
18  2015-07     28765.33
19  2015-08     36898.33
20  2015-09     64595.92
21  2015-10     31404.92
22  2015-11     75972.56
23  2015-12     74919.52
24  2016-01     18542.49
25  2016-02     22978.82
26  2016-03     51715.88
27  2016-04     38750.04
28  2016-05     56987.73
29  2016-06     40344.53
30  2016-07     39261.96
31  2016-08     31115.37
32  2016-09     73410.02
33  2016-10     59687.75
34  2016-11     79411.97
35  2016-12     96999.04
36  2017-01     43971.37
37  2017-02     20301.13
38  2017-03     58872.35
39  2017-04     36521.54
40  2017-05     44261.11
41  2017-06     52981.73
42  2017-07     45264.42
43  2017-08     63120.89
44  2017-09     87866.65
45  2017-10     77776.92
46  2017-11    118447.82
47  2017-12     83829.32

In [13]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("../data/cleaned_data.csv")

In [14]:
query = """
SELECT Category, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [15]:
query = """
    SQL goes here
"""

In [17]:
query = """
SELECT 
    strftime('%Y-%m', "Order Date") AS Month,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Month
ORDER BY Month;
"""

monthly_sales = pd.read_sql(query, engine)

monthly_sales

      Month  Total_Sales
0   2014-01     14236.90
1   2014-02      4519.89
2   2014-03     55691.01
3   2014-04     28295.35
4   2014-05     23648.29
5   2014-06     34595.13
6   2014-07     33946.39
7   2014-08     27909.47
8   2014-09     81777.35
9   2014-10     31453.39
10  2014-11     78628.72
11  2014-12     69545.62
12  2015-01     18174.08
13  2015-02     11951.41
14  2015-03     38726.25
15  2015-04     34195.21
16  2015-05     30131.69
17  2015-06     24797.29
18  2015-07     28765.33
19  2015-08     36898.33
20  2015-09     64595.92
21  2015-10     31404.92
22  2015-11     75972.56
23  2015-12     74919.52
24  2016-01     18542.49
25  2016-02     22978.82
26  2016-03     51715.88
27  2016-04     38750.04
28  2016-05     56987.73
29  2016-06     40344.53
30  2016-07     39261.96
31  2016-08     31115.37
32  2016-09     73410.02
33  2016-10     59687.75
34  2016-11     79411.97
35  2016-12     96999.04
36  2017-01     43971.37
37  2017-02     20301.13
38  2017-03     58872.35
39  2017-04     36521.54
40  2017-05     44261.11
41  2017-06     52981.73
42  2017-07     45264.42
43  2017-08     63120.89
44  2017-09     87866.65
45  2017-10     77776.92
46  2017-11    118447.82
47  2017-12     83829.32

In [18]:
query = """
SELECT 
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

category_sales = pd.read_sql(query, engine)

category_sales

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741999.80
2  Office Supplies    719047.03

In [20]:
query = """
SELECT 
    Region,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

region_sales = pd.read_sql(query, engine)

region_sales

    Region  Total_Sales
0     West    725457.82
1     East    678781.24
2  Central    501239.89
3    South    391721.91

In [21]:
query = """
SELECT 
    "Customer Name",
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query, engine)

top_customers

        Customer Name  Total_Sales
0         Sean Miller     25043.05
1        Tamara Chand     19052.22
2        Raymond Buch     15117.34
3        Tom Ashbrook     14595.62
4       Adrian Barton     14473.57
5        Ken Lonsdale     14175.23
6        Sanjit Chand     14142.33
7        Hunter Lopez     12873.30
8        Sanjit Engle     12209.44
9  Christopher Conant     12129.07

In [22]:
query = """
SELECT 
    "Product Name",
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

top_profit_products = pd.read_sql(query, engine)

top_profit_products

                                        Product Name  Total_Profit
0              Canon imageCLASS 2200 Advanced Copier      25199.93
1  Fellowes PB500 Electric Punch Plastic Comb Bin...       7753.04
2               Hewlett Packard LaserJet 3310 Copier       6983.88
3                 Canon PC1060 Personal Laser Copier       4570.93
4  HP Designjet T520 Inkjet Large Format Printer ...       4094.98
5                  Ativa V4110MDD Micro-Cut Shredder       3772.95
6   3D Systems Cube Printer, 2nd Generation, Magenta       3717.97
7  Plantronics Savi W720 Multi-Device Wireless He...       3696.28
8               Ibico EPK-21 Electric Binding System       3345.28
9                  Zebra ZM400 Thermal Label Printer       3343.54

In [23]:
query = """
SELECT 
    ROUND(SUM(Sales) / COUNT(DISTINCT "Order ID"), 2) AS Average_Order_Value
FROM sales;
"""

average_order = pd.read_sql(query, engine)

average_order

   Average_Order_Value
0               458.61

In [24]:
query = """
SELECT 
    "Product Name",
    SUM(Quantity) AS Total_Quantity
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Quantity DESC
LIMIT 10;
"""

top_quantity_products = pd.read_sql(query, engine)

top_quantity_products

                                        Product Name  Total_Quantity
0                                            Staples             215
1                                    Staple envelope             170
2                                  Easy-staple paper             150
3                            Staples in misc. colors              86
4                         KI Adjustable-Height Table              74
5                            Storex Dura Pro Binders              71
6                            Avery Non-Stick Binders              71
7  GBC Premium Transparent Covers with Diagonal L...              67
8         Situations Contoured Folding Chairs, 4/Set              64
9                         Staple-based wall hangings              62

In [25]:
query = """
SELECT 
    Segment,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

segment_sales = pd.read_sql(query, engine)

segment_sales

       Segment  Total_Sales
0     Consumer   1161401.34
1    Corporate    706146.37
2  Home Office    429653.15

In [26]:
query = """
WITH product_sales AS (
    SELECT
        Category,
        "Product Name",
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Category, "Product Name"
),
ranked_products AS (
    SELECT
        Category,
        "Product Name",
        ROUND(Total_Sales, 2) AS Total_Sales,
        RANK() OVER (
            PARTITION BY Category
            ORDER BY Total_Sales DESC
        ) AS Product_Rank
    FROM product_sales
)
SELECT
    Category,
    "Product Name",
    Total_Sales
FROM ranked_products
WHERE Product_Rank = 1
ORDER BY Category;
"""

top_category_products = pd.read_sql(query, engine)

top_category_products

,Category,Product Name,Total_Sales
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.58
1,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.38
2,Technology,Canon imageCLASS 2200 Advanced Copier,61599.82

In [27]:
query = """
WITH category_sales AS (
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Category
)
SELECT
    Category,
    ROUND(Total_Sales, 2) AS Total_Sales
FROM category_sales
ORDER BY Total_Sales DESC;
"""

cte_result = pd.read_sql(query, engine)

cte_result

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741999.80
2  Office Supplies    719047.03

In [28]:
query = """
SELECT
    Category,
    "Product Name",
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROW_NUMBER() OVER (
        PARTITION BY Category
        ORDER BY SUM(Sales) DESC
    ) AS Product_Number
FROM sales
GROUP BY Category, "Product Name";
"""

row_number_result = pd.read_sql(query, engine)

row_number_result.head(15)

,Category,Product Name,Total_Sales,Product_Number
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.58,1
1,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",15610.97,2
2,Furniture,Bretford Rectangular Conference Table Tops,12995.29,3
3,Furniture,Global Troy Executive Leather Low-Back Tilter,12975.38,4
4,Furniture,SAFCO Arco Folding Chair,11572.78,5
5,Furniture,DMI Eclipse Executive Suite Bookcases,11046.61,6
6,Furniture,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",10637.53,7
7,Furniture,Chromcraft Bull-Nose Wood Oval Conference Tabl...,9917.64,8
8,Furniture,Bush Advantage Collection Racetrack Conference...,9544.73,9
9,Furniture,GuestStacker Chair with Chrome Finish Legs,9070.94,10
10,Furniture,Office Star - Professional Matrix Back Chair w...,8774.50,11
11,Furniture,Global Deluxe High-Back Manager's Chair,8665.19,12
12,Furniture,Hon 4070 Series Pagoda Armless Upholstered Sta...,8431.00,13
13,Furniture,Chromcraft Round Conference Tables,8209.06,14
14,Furniture,Global Commerce Series High-Back Swivel/Tilt C...,7979.44,15

In [29]:
query = """
SELECT
    Category,
    "Product Name",
    ROUND(SUM(Sales), 2) AS Total_Sales,
    RANK() OVER (
        PARTITION BY Category
        ORDER BY SUM(Sales) DESC
    ) AS Sales_Rank
FROM sales
GROUP BY Category, "Product Name";
"""

rank_result = pd.read_sql(query, engine)

rank_result.head(15)

,Category,Product Name,Total_Sales,Sales_Rank
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.58,1
1,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",15610.97,2
2,Furniture,Bretford Rectangular Conference Table Tops,12995.29,3
3,Furniture,Global Troy Executive Leather Low-Back Tilter,12975.38,4
4,Furniture,SAFCO Arco Folding Chair,11572.78,5
5,Furniture,DMI Eclipse Executive Suite Bookcases,11046.61,6
6,Furniture,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",10637.53,7
7,Furniture,Chromcraft Bull-Nose Wood Oval Conference Tabl...,9917.64,8
8,Furniture,Bush Advantage Collection Racetrack Conference...,9544.73,9
9,Furniture,GuestStacker Chair with Chrome Finish Legs,9070.94,10
10,Furniture,Office Star - Professional Matrix Back Chair w...,8774.50,11
11,Furniture,Global Deluxe High-Back Manager's Chair,8665.19,12
12,Furniture,Hon 4070 Series Pagoda Armless Upholstered Sta...,8431.00,13
13,Furniture,Chromcraft Round Conference Tables,8209.06,14
14,Furniture,Global Commerce Series High-Back Swivel/Tilt C...,7979.44,15

In [30]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Month
)
SELECT
    Month,
    ROUND(Total_Sales, 2) AS Total_Sales,
    ROUND(
        LAG(Total_Sales) OVER (ORDER BY Month), 2
    ) AS Previous_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

lag_result = pd.read_sql(query, engine)

lag_result.head(15)

      Month  Total_Sales  Previous_Month_Sales
0   2014-01     14236.90                   NaN
1   2014-02      4519.89              14236.90
2   2014-03     55691.01               4519.89
3   2014-04     28295.35              55691.01
4   2014-05     23648.29              28295.35
5   2014-06     34595.13              23648.29
6   2014-07     33946.39              34595.13
7   2014-08     27909.47              33946.39
8   2014-09     81777.35              27909.47
9   2014-10     31453.39              81777.35
10  2014-11     78628.72              31453.39
11  2014-12     69545.62              78628.72
12  2015-01     18174.08              69545.62
13  2015-02     11951.41              18174.08
14  2015-03     38726.25              11951.41

In [31]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Month
)
SELECT
    Month,
    ROUND(Total_Sales, 2) AS Total_Sales,
    ROUND(
        LEAD(Total_Sales) OVER (ORDER BY Month), 2
    ) AS Next_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

lead_result = pd.read_sql(query, engine)

lead_result.head(15)

      Month  Total_Sales  Next_Month_Sales
0   2014-01     14236.90           4519.89
1   2014-02      4519.89          55691.01
2   2014-03     55691.01          28295.35
3   2014-04     28295.35          23648.29
4   2014-05     23648.29          34595.13
5   2014-06     34595.13          33946.39
6   2014-07     33946.39          27909.47
7   2014-08     27909.47          81777.35
8   2014-09     81777.35          31453.39
9   2014-10     31453.39          78628.72
10  2014-11     78628.72          69545.62
11  2014-12     69545.62          18174.08
12  2015-01     18174.08          11951.41
13  2015-02     11951.41          38726.25
14  2015-03     38726.25          34195.21

In [32]:
query = """
CREATE VIEW IF NOT EXISTS monthly_sales_view AS
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Month;
"""

with engine.connect() as connection:
    connection.exec_driver_sql(query)

print("View created successfully!")

View created successfully!

In [33]:
query = """
SELECT *
FROM monthly_sales_view
ORDER BY Month;
"""

view_result = pd.read_sql(query, engine)

view_result.head(10)

     Month  Total_Sales
0  2014-01     14236.90
1  2014-02      4519.89
2  2014-03     55691.01
3  2014-04     28295.35
4  2014-05     23648.29
5  2014-06     34595.13
6  2014-07     33946.39
7  2014-08     27909.47
8  2014-09     81777.35
9  2014-10     31453.39

In [1]:
import sys
sys.path.insert(0, "..")

from scripts.database_utils import get_engine, run_query

engine = get_engine()

print("Database connection successful!")

Database connection successful!

In [2]:
result = run_query("""
SELECT 
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
""")

result

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741999.80
2  Office Supplies    719047.03